#!/usr/bin/env python3
'''
How many distinct terms are in the sequence generated by a**b
For 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
'''


def get_terms():
    """
    Find the terms and put them in a list, return the set of list
    """
    lst = []
    for a in range(2, 101):
        for b in range(2, 101):
            term = (a ** b)
            lst.append(term)
    return set(lst)


def main():
    x = get_terms()
    print(len(x))

if __name__ == '__main__':
    main()
